version: '3'
services:

  #Laravel App
  simanot-app:
    build:
      args:
        user: inot
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: inouttt/laravel
    container_name: simanot-app-container
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - mynet

  #~Nginx Service
  simanot-nginx:
    image: nginx:alpine
    container_name: simanot-nginx-container
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/ssl/:/etc/nginx/ssl/
    networks:
      - mynet
  
  # node
  npm:
    image: node:12-alpine
    container_name: npm
    working_dir: /var/www/html
    entrypoint:
      - /init-scripts/node_start.sh
    volumes:
      - ./:/var/www/html
      - ./docker/init-scripts/:/init-scripts/
    networks: 
      - mynet
        # entrypoint: ['npm', '--no-bin-links']

  #MySQL Service
  simanot-db:
    image: mysql:5.7
    container_name: simanot-db-container
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: simanot
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    volumes:
      - mysqldata:/var/lib/mysql/
    networks:
      - mynet

#Docker Networks
networks:
  mynet:
    driver: bridge
#Volumes
volumes:
  mysqldata:
    driver: local