version: '3'
services:

  #Laravel App
  simanot-app:
    build:
      args:
        user: inot
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: inouttt/laravel
    container_name: simanot-app-container
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - mynet

  #Nginx Service
  # nginx:
  #   image: nginx:alpine
  #   container_name: simanot-nginx
  #   restart: unless-stopped
  #   tty: true
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./:/var/www/html
  #     - ./nginx/conf.d/:/etc/nginx/conf.d/
  #     - ./nginx/ssl/:/etc/nginx/ssl/
  #   networks:
  #     - mynet

  #MySQL Service
  simanot-db:
    image: mysql:5.7
    container_name: simanot-db-container
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: simanot
      MYSQL_USER: root
      MYSQL_PASSWORD: 
      MYSQL_ROOT_PASSWORD: 
    volumes:
      - mysqldata:/var/lib/mysql/
    networks:
      - mynet

#Docker Networks
networks:
  mynet:
    driver: bridge
#Volumes
volumes:
  mysqldata:
    driver: local